name: Swift

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,name=iPhone 11 Pro']
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build and Test
      run: |
        fastlane run scan
        
      env: 
        destination: ${{ matrix.destination }}
