name: Swift

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator, id=D24B8183-F18A-4A00-87FD-8B49D06619A6, OS=14.4, name=iPhone 8']
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build and Test
      run: |
        xcodebuild -project Musicall.xcodeproj \
              -scheme Musicall \
              -destination "${destination}" \
              clean test | xcpretty
        bash <(curl -s https://codecov.io/bash)
        
      env: 
        destination: ${{ matrix.destination }}
