name: Swift

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build and Test
      run: |
        xcodebuild -project Musicall.xcodeproj \
            -scheme Musicall\
            -destination platform="iOS Simulator", id:6411260A-0960-47A1-9F3B-D03A0406D26F, OS:14.4, name:"iPhone 11" \
            clean test | xcpretty
